name: dart
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  mongo_dart: ^0.7.4
  alfred: ^0.1.5+3

dev_dependencies:
  lints: ^1.0.0
